version: 2
jobs:
  build:
    working_directory: ~/react-template
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run build
          command: yarn build
      - run:
          name: Run lint
          command: yarn lint:eslint
      - run:
          name: Run tests
          command: yarn test
      - add_ssh_keys:
          fingerprints:
            - "3f:ba:0c:2c:1f:e7:e6:5d:10:02:6a:ad:b5:ed:4f:3e"
      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git config user.email "mac@wednesday.is"
              git config user.name "mac"
              yarn deploy ci skip
            fi